on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

name: Update release

jobs:
  update:
    name: update
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Scoop
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"

      - name: Auto-PR
        run: |
          ./bin/auto-pr.ps1 -r
